- name: Create simple_invoices database on RDS
  mysql_db:
    name: "{{ simpleinvoice_dbname }}"
    login_host: "{{ simpleinvoice_dbhost }}"
    login_user: "{{ simple_aws_dbuser }}"
    login_password: "{{ simple_aws_dbpass }}"
    state: present
  
