- name: Remove default html index
  file: 
    path: {{ simpleinvoice_home }}/html.index
    state: absent

- name: Unarchive {{ simpleinvoice_artifact }}
  unarchive:
    src: "/tmp/{{ simpleinvoice_artifact }}"
    dest: "{{ simpleinvoice_home }}"
    copy: no
    creates: "{{ simpleinvoice_home }}/simpleinvoice"
