- name: Remove default html index
  file: 
    path: "{{ simpleinvoice_home }}/index.html"
    state: absent

- name: Unarchive {{ simpleinvoice_artifact }}
  unarchive:
    src: "/tmp/{{ simpleinvoice_artifact }}"
    dest: "{{ simpleinvoice_home }}"
    copy: no
    creates: "{{ simpleinvoice_home }}/simpleinvoices/index.php"

- name: Change ownership to apache webserver user
  file:
    path: "{{ simpleinvoice_home }}"
    state: directory
    recurse: yes
    owner: www-data
    group: www-data

- name: Change permissions on tmp directory
  file:
    path: "{{ simpleinvoice_home }}/simpleinvoices/tmp"
    state: directory
    recurse: yes
    mode: 0775

- name: Create config.ini
  template:
    src: config.ini.j2
    dest: "{{ simpleinvoice_home }}/simpleinvoices/config/config.ini"
    force: yes
    owner: www-data
    group: www-data
