- name: Remove default html index
  file: 
    path: {{ simpleinvoice_home }}/html.index
    state: absent

- name: Unarchive {{ simpleinvoice_artifact }}
  unarchive:
    src: "/tmp/{{ simpleinvoice_artifact }}"
    dest: "{{ simpleinvoice_home }}"
    copy: no
    creates: "{{ simpleinvoice_home }}/simpleinvoice/index.php"

- name: Change ownership to apache webserver user
  file:
    path: {{ simpleinvoice_home }}/simpleinvoice
    recurse: yes
    owner: www-data
    group: www-data

- name: Change permissions on tmp directory
  file:
    path: {{ simpleinvoice_home/simpleinvoice/tmp
    recurse: yes
    mode: 777 
